name: Playwright Tests

jobs:
  e2e-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      # Also generates next-env.d.ts, required for tsc
      - name: Build localhost
        run: yarn build
      - name: Run TypeScript Compiler
        run: yarn tsc
      - name: Run ESLint
        run: yarn eslint . --max-warnings 0
      - name: Run Stylelint
        run: yarn stylelint '**/*.{css,scss,less,js,tsx}'
      - name: Install Playwright
        run: yarn playwright install --with-deps chromium
      - name: Run tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-screenshots-videos
          path: playwright/test-results/
  # deploy:
  #   name: Deploy to Fly.io
  #   runs-on: ubuntu-latest
  #   needs: e2e-tests
  #   if: github.ref == 'refs/heads/main'
  #   env:
  #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: superfly/flyctl-actions/setup-flyctl@master
  #     - run: flyctl deploy --remote-only
